"""Generate the web dev fixtures from real `phishpred publish` output.

The offline dev/build fixtures (`web/src/fixtures/generated.ts`) are the app's
fallback when there's no live Worker API. Deriving them from real published
artifacts (instead of hand-authored sample data) keeps the preview truthful:
every future show has real predictions and is clickable, and the tour table's
play-count distributions are the model's actual numbers.

Usage (from repo root, after `phishpred publish --out build/snapshots`):
    python -m uv run python scripts/gen_web_fixtures.py [build/snapshots]

Rows are trimmed (per-show / tour) to keep the JS bundle reasonable.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SHOW_TOP = 50          # per-show candidate rows kept in the fixture
TOUR_TOP = 150         # tour-table rows kept in the fixture
PLACEHOLDER_TOURS = [  # design pills for tours without cached data yet
    {"id": "fall-2026", "tour_name": "2026 Fall Tour", "has_data": False},
    {"id": "new-years-2026", "tour_name": "New Year's Run 2026", "has_data": False},
]


def main() -> None:
    snap = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("build/snapshots")
    out = Path("web/src/fixtures/generated.ts")

    def load(rel: str):
        return json.loads((snap / rel).read_text(encoding="utf-8"))

    meta = load("meta.json")
    schedule = load("schedule.json")
    tour = load("tour.json")
    tour["rows"] = tour["rows"][:TOUR_TOP]

    shows: dict[str, dict] = {}
    setlists: dict[str, dict] = {}
    for s in schedule["shows"]:
        if not s["has_data"]:
            continue
        d = s["showdate"]
        show = load(f"show/{d}.json")
        for src in show["sources"].values():
            src["rows"] = src["rows"][:SHOW_TOP]
        shows[d] = show
        setlists[d] = load(f"setlist/{d}.json")

    have = {t["id"] for t in meta["tours"]}
    for p in PLACEHOLDER_TOURS:
        if p["id"] not in have:
            meta["tours"].append(p)

    def const(name: str, obj, typ: str) -> str:
        return f"export const {name} = ({json.dumps(obj, ensure_ascii=False)}) as unknown as {typ};\n"

    body = "".join([
        "/* AUTO-GENERATED by scripts/gen_web_fixtures.py from build/snapshots.\n"
        "   Do not edit by hand — re-run the generator after `phishpred publish`. */\n",
        'import type { Meta, Schedule, ShowReport, TourReport, SetlistPrediction } from "../types";\n\n',
        const("genMeta", meta, "Meta"),
        const("genSchedule", schedule, "Schedule"),
        const("genTour", tour, "TourReport"),
        const("genShows", shows, "Record<string, ShowReport>"),
        const("genSetlists", setlists, "Record<string, SetlistPrediction>"),
    ])
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out} — {len(shows)} shows, {len(tour['rows'])} tour rows")


if __name__ == "__main__":
    main()
